name: PolymerMobileCodelab
description: A sample web application
dependencies:
  browser: any
  polymer: ">=0.15.1+3 <0.16.0"
  core_elements: ">=0.4.0+5 <0.5.0"
  paper_elements: ">=0.5.0 <0.6.0"

dev_dependencies:
  unittest: ">=0.11.0+5 <0.12.0"
    
environment:
  sdk: '>=1.5.1 <2.0.0'

transformers:
- polymer:
    entry_points:
    - web/begin/index.html
    - web/step2/index.html
    - web/step3/index.html    
    - web/step4/index.html
    - web/step5/index.html         
    - web/step6/index.html    
